### ISSUE TITLE
DRS 

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-mana#3]
[PRACTICA1_ELICITACION_DE_REQUISITOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-mana/files/14315614/PRACTICA1_ELICITACION_DE_REQUISITOS.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
